version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3 # 8.2.x broken thru at least 8.2.1, https://github.com/CircleCI-Public/aws-ecr-orb/issues/256#event-9613647282
  aws-ecs: circleci/aws-ecs@3.2.0
  jira: circleci/jira@1.3.1
  slack: circleci/slack@4.12.5

workflows:
  deploy-staging:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - develop
          context:
            - ecs-deploys
          repo: '${AWS_ECR_REPO_NAME}'
          region: '${AWS_REGION}'
          tag: 'staging,staging-${CIRCLE_SHA1}'
#      - aws-ecs/deploy-service-update:
#          context:
#            - ecs-deploys
#            - jira
#            - slack
#          requires:
#            - aws-ecr/build-and-push-image
#          aws-region: AWS_REGION
#          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}' # also sets `service`
#          cluster: 'tbg-staging-${AWS_REGION}'
#          container-image-name-updates: 'container=mautic_web,tag=staging-${CIRCLE_SHA1}'
#          post-steps:
#            - slack/notify:
#                event: fail
#                template: basic_fail_1
#            - jira/notify:
#                job_type: deployment
#                environment_type: staging
#            - slack/notify:
#                custom: |
#                  {
#                    "blocks": [
#                      {
#                        "type": "section",
#                        "fields": [
#                          {
#                            "type": "mrkdwn",
#                            "text": "*Staging: Mautic deployed!* You should see the updated app version within 30 minutes."
#                          }
#                        ]
#                      }
#                    ]
#                  }
  deploy-production:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - main
          context:
            - ecs-deploys
          repo: '${AWS_ECR_REPO_NAME}'
          region: '${AWS_REGION}'
          tag: 'production,production-${CIRCLE_SHA1}'
#      - aws-ecs/deploy-service-update:
#          context:
#            - ecs-deploys
#            - jira
#            - slack
#          requires:
#            - aws-ecr/build-and-push-image
#          aws-region: AWS_REGION
#          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}' # also sets `service`
#          cluster: 'tbg-production-${AWS_REGION}'
#          container-image-name-updates: 'container=mautic_web,tag=production-${CIRCLE_SHA1}'
#          post-steps:
#            - slack/notify:
#                event: fail
#                template: basic_fail_1
#            - jira/notify:
#                job_type: deployment
#                environment_type: production
#            - slack/notify:
#                custom: |
#                  {
#                    "blocks": [
#                      {
#                        "type": "section",
#                        "fields": [
#                          {
#                            "type": "mrkdwn",
#                            "text": "*Production: Mautic deployed!* You should see the updated app version within 30 minutes."
#                          }
#                        ]
#                      }
#                    ]
#                  }
